[package]
name = "CCIP_ONRAMP"
edition = "2024.beta"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }

[addresses]
ccip_onramp = "0x0"
ccip = "0x324c505732fadfa5ac2877cdca28a6be28910009e100de8e6e16eb33ed1218dc"

[dev-addresses]
ccip_onramp = "0x4000"
ccip = "0x3000"
