// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package firedrill_offramp

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EmitSourceChainAdded is the `emitSourceChainAdded` instruction.
type EmitSourceChainAdded struct {

	// [0] = [WRITE] offramp
	//
	// [1] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEmitSourceChainAddedInstructionBuilder creates a new `EmitSourceChainAdded` instruction builder.
func NewEmitSourceChainAddedInstructionBuilder() *EmitSourceChainAdded {
	nd := &EmitSourceChainAdded{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetOfframpAccount sets the "offramp" account.
func (inst *EmitSourceChainAdded) SetOfframpAccount(offramp ag_solanago.PublicKey) *EmitSourceChainAdded {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(offramp).WRITE()
	return inst
}

// GetOfframpAccount gets the "offramp" account.
func (inst *EmitSourceChainAdded) GetOfframpAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" account.
func (inst *EmitSourceChainAdded) SetOwnerAccount(owner ag_solanago.PublicKey) *EmitSourceChainAdded {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *EmitSourceChainAdded) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst EmitSourceChainAdded) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EmitSourceChainAdded,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EmitSourceChainAdded) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EmitSourceChainAdded) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Offramp is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *EmitSourceChainAdded) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EmitSourceChainAdded")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("offramp", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  owner", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj EmitSourceChainAdded) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EmitSourceChainAdded) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEmitSourceChainAddedInstruction declares a new EmitSourceChainAdded instruction with the provided parameters and accounts.
func NewEmitSourceChainAddedInstruction(
	// Accounts:
	offramp ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *EmitSourceChainAdded {
	return NewEmitSourceChainAddedInstructionBuilder().
		SetOfframpAccount(offramp).
		SetOwnerAccount(owner)
}
