// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package firedrill_offramp

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateOnRamp is the `updateOnRamp` instruction.
type UpdateOnRamp struct {

	// [0] = [WRITE] offramp
	//
	// [1] = [WRITE] sourceChain
	//
	// [2] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateOnRampInstructionBuilder creates a new `UpdateOnRamp` instruction builder.
func NewUpdateOnRampInstructionBuilder() *UpdateOnRamp {
	nd := &UpdateOnRamp{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetOfframpAccount sets the "offramp" account.
func (inst *UpdateOnRamp) SetOfframpAccount(offramp ag_solanago.PublicKey) *UpdateOnRamp {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(offramp).WRITE()
	return inst
}

// GetOfframpAccount gets the "offramp" account.
func (inst *UpdateOnRamp) GetOfframpAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSourceChainAccount sets the "sourceChain" account.
func (inst *UpdateOnRamp) SetSourceChainAccount(sourceChain ag_solanago.PublicKey) *UpdateOnRamp {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(sourceChain).WRITE()
	return inst
}

// GetSourceChainAccount gets the "sourceChain" account.
func (inst *UpdateOnRamp) GetSourceChainAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetOwnerAccount sets the "owner" account.
func (inst *UpdateOnRamp) SetOwnerAccount(owner ag_solanago.PublicKey) *UpdateOnRamp {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *UpdateOnRamp) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst UpdateOnRamp) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateOnRamp,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateOnRamp) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateOnRamp) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Offramp is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SourceChain is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *UpdateOnRamp) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateOnRamp")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    offramp", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("sourceChain", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      owner", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj UpdateOnRamp) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *UpdateOnRamp) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewUpdateOnRampInstruction declares a new UpdateOnRamp instruction with the provided parameters and accounts.
func NewUpdateOnRampInstruction(
	// Accounts:
	offramp ag_solanago.PublicKey,
	sourceChain ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *UpdateOnRamp {
	return NewUpdateOnRampInstructionBuilder().
		SetOfframpAccount(offramp).
		SetSourceChainAccount(sourceChain).
		SetOwnerAccount(owner)
}
