[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
failing_receiver = "26qpAicnGsqYijAKtKkiD2mRwo3JTaUdDxVwLxT7nujm"
firedrill_entrypoint = "7QHnC8L6vFK55jj4g6DNDcyfZQboGGMXi7rk8NEPEDs9"
firedrill_feequoter = "8y39U4xMcKnPP1NyWdYCEFTuCgZ18STYgeCxsjnSVcHm"
firedrill_offramp = "5asxTLb5cbDHnNdhTMNfLecMeJHFvbCfrvuqxVjeCqTR"

[programs.mainnet]
failing_receiver = "26qpAicnGsqYijAKtKkiD2mRwo3JTaUdDxVwLxT7nujm"
firedrill_entrypoint = "7QHnC8L6vFK55jj4g6DNDcyfZQboGGMXi7rk8NEPEDs9"
firedrill_feequoter = "8y39U4xMcKnPP1NyWdYCEFTuCgZ18STYgeCxsjnSVcHm"
firedrill_offramp = "5asxTLb5cbDHnNdhTMNfLecMeJHFvbCfrvuqxVjeCqTR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/bukata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
