[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
failing_receiver = "2qK8FXM4ri8Fzv1sesxo1PrCS6NqX5AM1qF8Yhh5E3TR"
firedrill_entrypoint = "2kJTe1XWyb5EUoWFYEp3UwujceJkJ2SNGPjbD5dWEY7n"
firedrill_feequoter = "6GyN8oxTLKib8qHrNvSby2TT5uAexqWHJ7NoAPZVBwxk"
firedrill_offramp = "APXXVut5KxNW6bMPwVQtvYTqxY2ZyHMxyUXWnTiQqGvb"

[programs.mainnet]
failing_receiver = "2qK8FXM4ri8Fzv1sesxo1PrCS6NqX5AM1qF8Yhh5E3TR"
firedrill_entrypoint = "2kJTe1XWyb5EUoWFYEp3UwujceJkJ2SNGPjbD5dWEY7n"
firedrill_feequoter = "6GyN8oxTLKib8qHrNvSby2TT5uAexqWHJ7NoAPZVBwxk"
firedrill_offramp = "APXXVut5KxNW6bMPwVQtvYTqxY2ZyHMxyUXWnTiQqGvb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/bukata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
