// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package firedrill_compound

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EmitUsdPerTokenUpdated is the `emitUsdPerTokenUpdated` instruction.
type EmitUsdPerTokenUpdated struct {

	// [0] = [WRITE] compound
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEmitUsdPerTokenUpdatedInstructionBuilder creates a new `EmitUsdPerTokenUpdated` instruction builder.
func NewEmitUsdPerTokenUpdatedInstructionBuilder() *EmitUsdPerTokenUpdated {
	nd := &EmitUsdPerTokenUpdated{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetCompoundAccount sets the "compound" account.
func (inst *EmitUsdPerTokenUpdated) SetCompoundAccount(compound ag_solanago.PublicKey) *EmitUsdPerTokenUpdated {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(compound).WRITE()
	return inst
}

// GetCompoundAccount gets the "compound" account.
func (inst *EmitUsdPerTokenUpdated) GetCompoundAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst EmitUsdPerTokenUpdated) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EmitUsdPerTokenUpdated,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EmitUsdPerTokenUpdated) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EmitUsdPerTokenUpdated) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Compound is not set")
		}
	}
	return nil
}

func (inst *EmitUsdPerTokenUpdated) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EmitUsdPerTokenUpdated")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("compound", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj EmitUsdPerTokenUpdated) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EmitUsdPerTokenUpdated) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEmitUsdPerTokenUpdatedInstruction declares a new EmitUsdPerTokenUpdated instruction with the provided parameters and accounts.
func NewEmitUsdPerTokenUpdatedInstruction(
	// Accounts:
	compound ag_solanago.PublicKey) *EmitUsdPerTokenUpdated {
	return NewEmitUsdPerTokenUpdatedInstructionBuilder().
		SetCompoundAccount(compound)
}
