// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package firedrill_token

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
)

type FiredrillToken struct{}

var FiredrillTokenDiscriminator = [8]byte{6, 159, 188, 18, 243, 108, 107, 81}

func (obj FiredrillToken) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(FiredrillTokenDiscriminator[:], false)
	if err != nil {
		return err
	}
	return nil
}

func (obj *FiredrillToken) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(FiredrillTokenDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[6 159 188 18 243 108 107 81]",
				fmt.Sprint(discriminator[:]))
		}
	}
	return nil
}
