[profile.default]
solc_version = "0.8.24"
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/=lib/ccip/contracts/src/v0.8",
    "forge-std/=lib/forge-std/src/",
]

